name: Build-Windows-YYC
on: 
  # push: #Uncomment this line to run the workflow on push
  workflow_dispatch: #This line allows you to run the workflow manually from the GitHub Actions page
  workflow_call: #This line allows you to run the workflow from another workflow
jobs:
  build:
    runs-on: windows-2022
    steps:
      # Check out the repository with the GameMaker project
      - uses: actions/checkout@v4
        with:
          lfs: true
      # This step finds the yyp file in the repository and saves the path to an output
      - id: find_yyp
        name: find-the-yyp-file
        run: |
          $yyp = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.yyp
          Write-Output "YYP file found at: $yyp"
          "yyp-path=$yyp" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      # This step sets up the GameMaker build CLI tool Igor https://github.com/bscotch/igor-setup
      - id: igor_setup
        name: setup-igor-environment
        uses: bscotch/igor-setup@v1.1.0
        with:
          runtime-version: 2023.11.1.160
          target-yyp: ${{ steps.find_yyp.outputs.yyp-path }}
          access-key: ${{ secrets.ACCESS_KEY }} # üìù To generate your Access Key, check out the Access Key section of the GameMaker Manual's Building via Command Line page: https://manual.gamemaker.io/monthly/en/#t=Settings%2FBuilding_via_Command_Line.htm
      # This step uses Igor to build the GameMaker project https://github.com/bscotch/igor-build
      - id: igor_build
        name: igor-build
        uses: bscotch/igor-build@v1.0.3
        with:
          yyp-path: ${{ steps.find_yyp.outputs.yyp-path }}
          user-dir: ${{ steps.igor_setup.outputs.user-dir }}
          yyc: false
      # This step uploads the build to the artifacts, so you can download it from the GitHub Actions page or use it in another workflow
      - id: get_date_time
        name: Get current date and time
        run: echo "::set-output name=date_time::$(date +'%d-%m-%Y-%H:%M')"
      - id: upload_artifact
        name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChapterMaster-Windows-${{ steps.get_date_time.outputs.date_time }}
          path: ${{ steps.igor_build.outputs.out-dir }}
          retention-days: 1 # Longer retention days can incur additional charges. See https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
          
